version: "3.9"
services:
  eureka-server:
    image: rpg-eureka-server:1.0
    ports:
      - "40000:40000"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  cloud-gateway:
    image: rpg-cloud-gateway:1.0
    ports:
      - "41000:41000"
    networks:
      app_net:
        ipv4_address: 172.16.238.20
  cloud-oauth2:
    image: rpg-cloud-oauth2:1.0
    ports:
      - "42000:42000"
    networks:
      app_net:
        ipv4_address: 172.16.238.30
  member-user:
    image: rpg-member-user:1.0
    ports:
      - "43000:43000"
    networks:
      app_net:
        ipv4_address: 172.16.238.40
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"