spring:
  application:
    name: ${APP_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-gateway
          uri: lb://rpg-cloud-oauth2
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=2
        - id: member-user
          uri: lb://rpg-member-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}@${REGISTRY_HOST}:${REGISTRY_PORT}/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
server:
  port: ${APP_PORT}
