FROM anapsix/alpine-java:8u201b09_server-jre_nashorn

MAINTAINER 1719341471@qq.com

WORKDIR /usr/local/src

CMD ["java","-jar","rpg-eureka-server.jar"]

EXPOSE 40000

ADD eureka/rpg-eureka-server.jar rpg-eureka-server.jar